%YAML 1.2
---
# http://www.sublimetext.com/docs/3/syntax.html
name: ${display_name}
file_extensions:
  - sublime-settings
scope: source.json, source.sublime-settings
contexts:
  main:
    - match: ""
      push: "${paths.require}"


