      gutter: '${palette.ui.gutter.hex}'
      gutterForeground: '${palette.ui.gutterForeground.hex}'

      tagsOptions: stippled_underline
      bracketsForeground: '#CCCC15'
      bracketsOptions: underline
      bracketContentsForeground: '#15CC15'
      bracketContentsOptions: underline

      caret: '${palette.edit.caret.hex}'
      lineHighlight: '${palette.edit.lineHighlight.hex}'

      findHighlight: '${palette.edit.findHighlight.hex}'
      findHighlightForeground: '${palette.edit.findHighlightForeground.hex}'

      selection: '${palette.edit.selection.hex}'
      selectionBorder: '${palette.edit.selectionBorder.hex}'
      inactiveSelection: '${palette.edit.inactiveSelection.hex}'

      invisibles: '${palette.edit.invisibles.hex}'

      guide: '#4E4E36'
      activeGuide: '#CC9D15CC'
      stackGuide: '#CC15CC80'

      highlight: '#9D15CCCC'
      highlightForeground: '#FFCCFF'

      popupCss: "html {
        background-color: #343424;
        color: #FFFFB2;
        padding: 16px;
      }
      a {
        color: #808041;
        display: block;
        text-decoration: none;
      }
      .error, .deleted {
        color: #992F2F;
      }
      .success, .inserted {
        color: #2F992F;
      }
      .warning, .modified {
        color: #99992F;
      }"

      shadow: '${palette.ui.shadow.hex}'
      shadowWidth: '30'

